language: ruby
dist: xenial
cache: bundler

addons:
  apt:
    packages:
    - squid

matrix:
  include:
    - rvm: 2.4
    - rvm: 2.5
    - rvm: 2.6
    - rvm: 2.6
      env: COVERAGE=BriefSummary,Coveralls
    - rvm: jruby-head
      env: JRUBY_OPTS="--debug -X+O"
    - rvm: truffleruby
    - rvm: ruby-head
    - rvm: 2.6
      env: CLOUDFLARE_PROXY=http://localhost:3128
      before_script: sudo service squid start
    - rvm: jruby-head
      env: JRUBY_OPTS="--debug -X+O" CLOUDFLARE_PROXY=http://localhost:3128
      before_script: sudo service squid start
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: truffleruby

env:
  global:
    - CLOUDFLARE_TEST_ZONE_MANAGEMENT=true
    - secure: c5yG7N1r9nYuw47Y90jGeoHNvkL59AAC55dtPAhKP+gjXWW8hKbntj3oj+lVkxEqzRpzEQgYZzUElrP+6mJnb20ldclZg03L56243tMtVEcpGOx/MFhnIBkx3kKu1H6ydKKMxieHxjsLQ3vnpcIZ3p0skTQjYbjdu607tjbyg7s=
